apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  # namespace: blog-app
  labels:
    app: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-pod
  template:
    metadata:
      name: flask-pod
      labels:
        app: flask-pod
    spec:
      containers:
        - name: flask-container
          image: coder336/flask-blog-app:289464761358ede64f8ef1d13d3a78a1dc3fa46e
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              # protocol: TCP
