apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  # namespace: blog-app
  labels:
    app: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-pod
  template:
    metadata:
      name: flask-pod
      labels:
        app: flask-pod
    spec:
      containers:
        - name: flask-container
          image: ${DOCKERHUB_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              # protocol: TCP
