apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  # namespace: blog-app
  labels:
    app: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-pod
  template:
    metadata:
      name: flask-pod
      labels:
        app: flask-pod
    spec:
      containers:
        - name: flask-container
          image: coder336/flask-blog-app:4b4df18bb4cb04f84b41282c683c7102661c55f0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              # protocol: TCP
